import type { PurchaseRequest, Quotation, Recommendation, Supplier } from "./types";

const today = new Date();
const inDays = (d: number) => new Date(today.getTime() + d * 86400000).toISOString();
const agoDays = (d: number) => new Date(today.getTime() - d * 86400000).toISOString();

export const SUPPLIERS: Supplier[] = [
  {
    id: "sup-tecnomyl",
    legal_name: "Tecnomyl SA",
    ruc: "80012345-6",
    primary_categories: ["fertilizante", "fitosanitario"],
    ml_p_on_time: 0.92,
    on_time_rate: 0.94,
    quotations_received: 48,
    awards: 22,
    last_activity: agoDays(2),
  },
  {
    id: "sup-agrofertil",
    legal_name: "Agrofertil",
    ruc: "80022134-1",
    primary_categories: ["fertilizante", "semilla"],
    ml_p_on_time: 0.81,
    on_time_rate: 0.83,
    quotations_received: 36,
    awards: 14,
    last_activity: agoDays(5),
  },
  {
    id: "sup-atlantic",
    legal_name: "Atlantic Comercio Agroindustrial",
    ruc: "80044921-3",
    primary_categories: ["fertilizante", "combustible"],
    ml_p_on_time: 0.55,
    on_time_rate: 0.61,
    quotations_received: 22,
    awards: 6,
    last_activity: agoDays(1),
  },
  {
    id: "sup-glymax",
    legal_name: "Glymax Paraguay",
    ruc: "80091188-7",
    primary_categories: ["fitosanitario", "fertilizante"],
    ml_p_on_time: 0.74,
    on_time_rate: 0.78,
    quotations_received: 31,
    awards: 11,
    last_activity: agoDays(7),
  },
  {
    id: "sup-ciabay",
    legal_name: "Ciabay SA",
    ruc: "80017734-9",
    primary_categories: ["maquinaria", "repuesto"],
    ml_p_on_time: 0.88,
    on_time_rate: 0.9,
    quotations_received: 19,
    awards: 8,
    last_activity: agoDays(11),
  },
  {
    id: "sup-dekalpar",
    legal_name: "Dekalpar SA",
    ruc: "80055120-4",
    primary_categories: ["semilla"],
    ml_p_on_time: 0.86,
    on_time_rate: 0.87,
    quotations_received: 25,
    awards: 12,
    last_activity: agoDays(3),
  },
];

const ureaItems = [
  {
    id: "it-urea-46",
    description: "Urea granulada 46% N — bolsas 50 kg",
    qty: 800,
    unit: "ton",
    spec: "Origen Egipto/Rusia. Humedad <0.5%. Biuret <1%.",
    target_price_pyg: 4_650_000,
  },
];

export const REQUESTS: PurchaseRequest[] = [
  {
    id: "req-urea-2627",
    title: "Compra de 800 ton de urea 46% para zafra soja 26/27",
    description:
      "Reposición estratégica de urea para socios productores antes de la ventana de aplicación V4-V6 en soja. Entrega escalonada en silos de Yguazú y Bella Vista.",
    category: "fertilizante",
    crop: "soja",
    zafra: "2026/27",
    fenological_window: "V4 — V6",
    hectares: 12_400,
    department: "Itapua",
    deadline: inDays(11),
    budget_pyg: 4_000_000_000,
    urgency: "alta",
    weights: { precio: 45, plazo: 25, calidad: 20, condiciones: 10 },
    items: ureaItems,
    status: "en_comparacion",
    created_at: agoDays(6),
    total_estimated_pyg: 3_720_000_000,
  },
  {
    id: "req-soja-rr",
    title: "Semilla soja RR — variedad NS 6909 IPRO",
    description: "Semilla certificada para 4.200 ha de socios del distrito de Hohenau.",
    category: "semilla",
    crop: "soja",
    zafra: "2026/27",
    fenological_window: "Pre-siembra",
    hectares: 4_200,
    department: "Itapua",
    deadline: inDays(22),
    budget_pyg: 1_650_000_000,
    urgency: "media",
    weights: { precio: 40, plazo: 20, calidad: 30, condiciones: 10 },
    items: [
      {
        id: "it-soja-1",
        description: "Semilla soja NS 6909 IPRO — bolsas 40 kg",
        qty: 168_000,
        unit: "kg",
        spec: "Germinación >85%, tratada Standak Top.",
        target_price_pyg: 9_200,
      },
    ],
    status: "publicada",
    created_at: agoDays(2),
    total_estimated_pyg: 1_545_600_000,
  },
  {
    id: "req-glifo",
    title: "Glifosato 48% — 60.000 L para barbecho",
    description: "Aplicación pre-siembra de soja en lotes de Capitán Miranda.",
    category: "fitosanitario",
    crop: "soja",
    zafra: "2026/27",
    fenological_window: "Barbecho",
    hectares: 7_800,
    department: "Itapua",
    deadline: inDays(5),
    budget_pyg: 540_000_000,
    urgency: "critica",
    weights: { precio: 35, plazo: 35, calidad: 20, condiciones: 10 },
    items: [
      {
        id: "it-glifo-1",
        description: "Glifosato sal de potasio 48% — tambor 200 L",
        qty: 60_000,
        unit: "L",
        spec: "Concentración mínima 480 g/L. Coadyuvante incluido.",
        target_price_pyg: 8_900,
      },
    ],
    status: "en_cotizacion",
    created_at: agoDays(3),
    total_estimated_pyg: 534_000_000,
  },
  {
    id: "req-diesel",
    title: "Diésel agrícola — 120.000 L para flota cosecha",
    description: "Reposición de combustible para tractores y cosechadoras.",
    category: "combustible",
    crop: "maiz",
    zafra: "2026/27",
    fenological_window: "Cosecha maíz zafriña",
    hectares: 3_500,
    department: "Alto Parana",
    deadline: inDays(15),
    budget_pyg: 950_000_000,
    urgency: "media",
    weights: { precio: 50, plazo: 25, calidad: 15, condiciones: 10 },
    items: [
      {
        id: "it-diesel-1",
        description: "Diésel agrícola B7",
        qty: 120_000,
        unit: "L",
        spec: "Norma ANP. Entrega en planta de almacenamiento.",
        target_price_pyg: 7_650,
      },
    ],
    status: "publicada",
    created_at: agoDays(1),
    total_estimated_pyg: 918_000_000,
  },
  {
    id: "req-sembradora",
    title: "Repuestos sembradora John Deere DB 60",
    description: "Mantenimiento pre-zafra de 4 sembradoras.",
    category: "repuesto",
    crop: "soja",
    zafra: "2026/27",
    fenological_window: "Pre-siembra",
    hectares: 0,
    department: "Itapua",
    deadline: inDays(30),
    budget_pyg: 180_000_000,
    urgency: "baja",
    weights: { precio: 30, plazo: 30, calidad: 30, condiciones: 10 },
    items: [
      {
        id: "it-rep-1",
        description: "Kit discos de corte + rolamientos",
        qty: 4,
        unit: "kit",
        spec: "OEM John Deere o equivalente certificado.",
        target_price_pyg: 38_500_000,
      },
    ],
    status: "borrador",
    created_at: agoDays(0),
    total_estimated_pyg: 154_000_000,
  },
];

export const QUOTATIONS: Quotation[] = [
  {
    id: "q-tecnomyl",
    request_id: "req-urea-2627",
    supplier_id: "sup-tecnomyl",
    total_pyg: 3_720_000_000,
    delivery_days: 12,
    warranty_months: 6,
    payment_terms: "30/60 días, sin recargo",
    ml_score: 88,
    ml_p_on_time: 0.92,
    anomaly: false,
    status: "validada",
    items: [{ item_id: "it-urea-46", unit_price_pyg: 4_650_000, qty: 800 }],
    notes: "Stock confirmado en puerto de Villeta.",
  },
  {
    id: "q-agrofertil",
    request_id: "req-urea-2627",
    supplier_id: "sup-agrofertil",
    total_pyg: 3_656_000_000,
    delivery_days: 18,
    warranty_months: 6,
    payment_terms: "Contado con 2% descuento o 30 días",
    ml_score: 76,
    ml_p_on_time: 0.81,
    anomaly: false,
    status: "validada",
    items: [{ item_id: "it-urea-46", unit_price_pyg: 4_570_000, qty: 800 }],
  },
  {
    id: "q-atlantic",
    request_id: "req-urea-2627",
    supplier_id: "sup-atlantic",
    total_pyg: 3_050_400_000,
    delivery_days: 22,
    warranty_months: 3,
    payment_terms: "Contado anticipado 100%",
    ml_score: 42,
    ml_p_on_time: 0.55,
    anomaly: true,
    anomaly_reason:
      "Precio 18% por debajo del promedio de mercado. Histórico de 3 entregas con atraso >15 días en últimos 12 meses.",
    status: "validada",
    items: [{ item_id: "it-urea-46", unit_price_pyg: 3_813_000, qty: 800 }],
  },
  {
    id: "q-glymax",
    request_id: "req-urea-2627",
    supplier_id: "sup-glymax",
    total_pyg: 3_792_000_000,
    delivery_days: 14,
    warranty_months: 6,
    payment_terms: "30 días",
    ml_score: 71,
    ml_p_on_time: 0.74,
    anomaly: false,
    status: "validada",
    items: [{ item_id: "it-urea-46", unit_price_pyg: 4_740_000, qty: 800 }],
  },
];

export const RECOMMENDATION: Recommendation = {
  request_id: "req-urea-2627",
  recommended_supplier_id: "sup-tecnomyl",
  decision_band: "alta_confianza",
  composite_score: 87,
  urgency_score: { total: 78, weather: 82, delivery: 75, volatility: 76 },
  offer_score: { total: 89, supplier: 92, terms: 88, delivery_risk: 86 },
  justification_md: `**Tecnomyl SA** ofrece el mejor balance entre precio competitivo y confiabilidad operativa para esta ventana fenológica V4–V6.

- Precio total **Gs. 3.720 M**, apenas **1,7% sobre la mejor oferta** validada.
- Plazo de entrega de **12 días**, el más corto entre proveedores con score ML > 80.
- Stock confirmado en puerto de Villeta — minimiza riesgo logístico previo a la ventana de aplicación.
- Probabilidad de entrega a tiempo **92%**, históricamente la más alta del mercado.`,
  alternatives_md: `- **Agrofertil** (Gs. 3.656 M) es 1,7% más barato pero con plazo de 18 días, marginal frente al deadline.
- **Glymax** (Gs. 3.792 M) tiene plazo similar pero 0,8% más caro y score ML inferior.
- **Atlantic** descartada por anomalía de precio (-18% vs mercado) y bajo p_on_time (55%).`,
  risks_md: `- **Volatilidad del PYG/USD** podría impactar pedidos no cerrados antes del 15 del mes.
- **Pronóstico climático** indica lluvias intensas en Itapúa días 8–10; coordinar entrega antes del día 7.
- Considerar **cláusula de penalidad** por atraso >5 días para proteger ventana V4–V6.`,
};
