/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ProveedoresRouteImport } from './routes/proveedores'
import { Route as NuevaRouteImport } from './routes/nueva'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as CargarRouteImport } from './routes/cargar'
import { Route as IndexRouteImport } from './routes/index'
import { Route as SolicitudIdRouteImport } from './routes/solicitud.$id'
import { Route as CompararIdRouteImport } from './routes/comparar.$id'

const ProveedoresRoute = ProveedoresRouteImport.update({
  id: '/proveedores',
  path: '/proveedores',
  getParentRoute: () => rootRouteImport,
} as any)
const NuevaRoute = NuevaRouteImport.update({
  id: '/nueva',
  path: '/nueva',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const CargarRoute = CargarRouteImport.update({
  id: '/cargar',
  path: '/cargar',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const SolicitudIdRoute = SolicitudIdRouteImport.update({
  id: '/solicitud/$id',
  path: '/solicitud/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const CompararIdRoute = CompararIdRouteImport.update({
  id: '/comparar/$id',
  path: '/comparar/$id',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/cargar': typeof CargarRoute
  '/dashboard': typeof DashboardRoute
  '/nueva': typeof NuevaRoute
  '/proveedores': typeof ProveedoresRoute
  '/comparar/$id': typeof CompararIdRoute
  '/solicitud/$id': typeof SolicitudIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/cargar': typeof CargarRoute
  '/dashboard': typeof DashboardRoute
  '/nueva': typeof NuevaRoute
  '/proveedores': typeof ProveedoresRoute
  '/comparar/$id': typeof CompararIdRoute
  '/solicitud/$id': typeof SolicitudIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/cargar': typeof CargarRoute
  '/dashboard': typeof DashboardRoute
  '/nueva': typeof NuevaRoute
  '/proveedores': typeof ProveedoresRoute
  '/comparar/$id': typeof CompararIdRoute
  '/solicitud/$id': typeof SolicitudIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/cargar'
    | '/dashboard'
    | '/nueva'
    | '/proveedores'
    | '/comparar/$id'
    | '/solicitud/$id'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/cargar'
    | '/dashboard'
    | '/nueva'
    | '/proveedores'
    | '/comparar/$id'
    | '/solicitud/$id'
  id:
    | '__root__'
    | '/'
    | '/cargar'
    | '/dashboard'
    | '/nueva'
    | '/proveedores'
    | '/comparar/$id'
    | '/solicitud/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  CargarRoute: typeof CargarRoute
  DashboardRoute: typeof DashboardRoute
  NuevaRoute: typeof NuevaRoute
  ProveedoresRoute: typeof ProveedoresRoute
  CompararIdRoute: typeof CompararIdRoute
  SolicitudIdRoute: typeof SolicitudIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/proveedores': {
      id: '/proveedores'
      path: '/proveedores'
      fullPath: '/proveedores'
      preLoaderRoute: typeof ProveedoresRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/nueva': {
      id: '/nueva'
      path: '/nueva'
      fullPath: '/nueva'
      preLoaderRoute: typeof NuevaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cargar': {
      id: '/cargar'
      path: '/cargar'
      fullPath: '/cargar'
      preLoaderRoute: typeof CargarRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/solicitud/$id': {
      id: '/solicitud/$id'
      path: '/solicitud/$id'
      fullPath: '/solicitud/$id'
      preLoaderRoute: typeof SolicitudIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/comparar/$id': {
      id: '/comparar/$id'
      path: '/comparar/$id'
      fullPath: '/comparar/$id'
      preLoaderRoute: typeof CompararIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  CargarRoute: CargarRoute,
  DashboardRoute: DashboardRoute,
  NuevaRoute: NuevaRoute,
  ProveedoresRoute: ProveedoresRoute,
  CompararIdRoute: CompararIdRoute,
  SolicitudIdRoute: SolicitudIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
